<a href="https://colab.research.google.com/github/fakhar-iqbal/Machine_Learning_Fundamentals/blob/main/Single_point_Regression_gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Gradient of single point regression**

## in this notebook, we calcuate the gradient of quadratic cost with respect to  straight line regression model's parameters.

In [1]:
import torch

In [2]:
xs = torch.tensor([0,1,2,3,4,5,6,7.])
ys  = torch.tensor([1.86,1.31,0.62,.33,.09,-.67,-1.23,-1.37])

##The slope of line is y= mx+ b

In [3]:
def regression(x,m,b):
  return m*x + b

In [4]:
m = torch.tensor([0.9]).requires_grad_()
b  = torch.tensor([0.1]).requires_grad_()

## to keep partial deriv as simple as possibke, we will go with single instance i in data points

In [5]:
i=7
x = xs[i]
y = ys[i]

In [6]:
x,y

(tensor(7.), tensor(-1.3700))

##**Step1: forward pass**

In [7]:
yhat = regression(x,m,b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

##**Step2: comparing the cost**

In [8]:
def squared_error(yhat,y):
  return (yhat-y)**2

In [11]:
C = squared_error(yhat,y)
C

tensor([60.3729], grad_fn=<PowBackward0>)

##**Step3: Autodiff to calc gradient of C wrt params**

In [12]:
C.backward()

In [13]:
m.grad

tensor([108.7800])

In [14]:
b.grad

tensor([15.5400])

$$ \frac{\partial C}{\partial m} = 2x(\hat{y} - y) $$

In [15]:
2 * x * (yhat-y)

tensor([108.7800], grad_fn=<MulBackward0>)

$$ \frac{\partial C}{\partial b} = 2(\hat{y}-y) $$

In [16]:
2 * (yhat-y)

tensor([15.5400], grad_fn=<MulBackward0>)

### The Gradient of Cost, $\nabla C$

The gradient of cost, which is symbolized $\nabla C$ (pronounced "nabla C"), is a vector of all the partial derivatives of $C$ with respect to each of the individual model parameters:

$\nabla C = \nabla_p C = \left[ \frac{\partial{C}}{\partial{p_1}}, \frac{\partial{C}}{\partial{p_2}}, \cdots, \frac{\partial{C}}{\partial{p_n}} \right]^T $

\In this case, there are only two parameters, $b$ and $m$:

$\nabla C = \left[ \frac{\partial{C}}{\partial{b}}, \frac{\partial{C}}{\partial{m}} \right]^T $

In [17]:
gradient = torch.tensor([[b.grad.item(),m.grad.item()]]).T

In [18]:
gradient

tensor([[ 15.5400],
        [108.7800]])